// hello world
GET http://localhost:3000/

#####

// Getting data from user
GET http://localhost:3000/users/admin
Content-Type: application/json

#####

// Post New User
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "user12",
    "password": "pass12"
}

####

// to login the user
POST http://localhost:3000/users/login/
Content-Type: application/json

{
    "username": "user12",
    "password": "pass12"
}

####

// to add a task
PUT http://localhost:3000/tasks/6692a8f6350b162893b2c913
Content-Type: application/json

{
    "taskName": "user12task1",
    "taskDescription": "taskdescription",
    "taskDue": "12.04.2024",
    "taskTags": []
}

#####

// To delete a task
PUT http://localhost:3000/tasks/delete/6692a8f6350b162893b2c913
Content-Type: application/json

{
    "deletedTaskId": 1
}

#######

// to add a tag
PUT http://localhost:3000/users/tags/6692a8f6350b162893b2c913
Content-Type: application/json

{
    "tagName": "user12tag1",
    "tagColor": "red"
}

#####

// to delete a tag
PUT http://localhost:3000/users/tags/delete/6692a8f6350b162893b2c913
Content-Type: application/json

{
    "deletedTagId": 1
}


#####

// Adding existing usertag to task
PUT http://localhost:3000/tasks/tags/add/6692a8f6350b162893b2c913
Content-Type: application/json

{
    "addTagTo": 0,
    "addedTag": 0
}

####

// Deleting tag from task
PUT http://localhost:3000/tasks/tags/delete/6692a8f6350b162893b2c913
Content-Type: application/json

{
    "deleteTagFrom": 0,
    "deletedTag": 0
}


###